// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GoogleAuth {
    /**
     * Creates a new GoogleAuth instance.
     * @param {Partial<GoogleAuth>} [$$source = {}] - The source object to create the GoogleAuth.
     */
    constructor($$source = {}) {
        if (!("TokenNeeded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["TokenNeeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoogleAuth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GoogleAuth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoogleAuth(/** @type {Partial<GoogleAuth>} */($$parsedSource));
    }
}
