// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as calendar$0 from "../../google.golang.org/api/calendar/v3/models.js";

export class AuthCodeToken {
    /**
     * Creates a new AuthCodeToken instance.
     * @param {Partial<AuthCodeToken>} [$$source = {}] - The source object to create the AuthCodeToken.
     */
    constructor($$source = {}) {
        if (!("Token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthCodeToken instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AuthCodeToken}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthCodeToken(/** @type {Partial<AuthCodeToken>} */($$parsedSource));
    }
}

export class CalendarEvents {
    /**
     * Creates a new CalendarEvents instance.
     * @param {Partial<CalendarEvents>} [$$source = {}] - The source object to create the CalendarEvents.
     */
    constructor($$source = {}) {
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {(calendar$0.Event | null)[]}
             */
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalendarEvents instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalendarEvents}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField0_0($$parsedSource["events"]);
        }
        return new CalendarEvents(/** @type {Partial<CalendarEvents>} */($$parsedSource));
    }
}

export class GoogleAuth {
    /**
     * Creates a new GoogleAuth instance.
     * @param {Partial<GoogleAuth>} [$$source = {}] - The source object to create the GoogleAuth.
     */
    constructor($$source = {}) {
        if (!("TokenNeeded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["TokenNeeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoogleAuth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GoogleAuth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoogleAuth(/** @type {Partial<GoogleAuth>} */($$parsedSource));
    }
}

export class Transcription {
    /**
     * Creates a new Transcription instance.
     * @param {Partial<Transcription>} [$$source = {}] - The source object to create the Transcription.
     */
    constructor($$source = {}) {
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("IsFinal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsFinal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Transcription instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Transcription}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Transcription(/** @type {Partial<Transcription>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
