/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoogleAuthRouteImport } from './routes/google-auth'
import { Route as AudioSearchRouteImport } from './routes/audio-search'
import { Route as IndexRouteImport } from './routes/index'

const GoogleAuthRoute = GoogleAuthRouteImport.update({
  id: '/google-auth',
  path: '/google-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioSearchRoute = AudioSearchRouteImport.update({
  id: '/audio-search',
  path: '/audio-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-search': typeof AudioSearchRoute
  '/google-auth': typeof GoogleAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-search': typeof AudioSearchRoute
  '/google-auth': typeof GoogleAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-search': typeof AudioSearchRoute
  '/google-auth': typeof GoogleAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audio-search' | '/google-auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio-search' | '/google-auth'
  id: '__root__' | '/' | '/audio-search' | '/google-auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioSearchRoute: typeof AudioSearchRoute
  GoogleAuthRoute: typeof GoogleAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/google-auth': {
      id: '/google-auth'
      path: '/google-auth'
      fullPath: '/google-auth'
      preLoaderRoute: typeof GoogleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-search': {
      id: '/audio-search'
      path: '/audio-search'
      fullPath: '/audio-search'
      preLoaderRoute: typeof AudioSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioSearchRoute: AudioSearchRoute,
  GoogleAuthRoute: GoogleAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
